### ISSUE TITLE
Inference Qwen1.5-110b on Gaudi2

### ISSUE THREAD

**Issue by Deegue** [intel/llm-on-ray#248]
When deploying model with 8 cards on Gaudi2 node, sometimes it will report OOM from Ray:

> (raylet) A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff3ceaaf70d0335e055712140f01000000 Worker ID: e1fd96e8f235b1f82cfb2f559cb759e25416b3e75d7ae327f2eec4a0 Node ID: ab4de64cf90612fcbc8bc46787bebf86fdc9dbdb783237171b69f063 Worker IP address: 100.83.111.234 Worker port: 10162 Worker PID: 15295 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

It is due to using single card though the config is 8 cards.

When successfully deployed, memory usage will be like:
![image](https://github.com/intel/llm-on-ray/assets/25916266/c9a6930a-b92b-44f0-96bb-650f422ba046)

It used 4 cards with 32G memory each.
The model deployed successfully, but query will hang and fail with http 500:
Client log:

> root@aise-cluster-03-2:~/llm-on-ray# python examples/inference/api_server_openai/query_http_requests.py --model_name Qwen1.5-110B 
chunk content:  {"generated_text":null,"tool_calls":null,"num_input_tokens":null,"num_input_tokens_batch":null,"num_generated_tokens":null,"num_generated_tokens_batch":null,"preprocessing_time":null,"generation_time":null,"timestamp":1718088350.7864213,"finish_reason":null,"error":{"object":"error","message":"Internal Server Error","internal_message":"Internal Server Error","type":"InternalServerError","param":{},"code":500},"num_total_tokens":0,"num_total_tokens_batch":0,"total_time":null}
Traceback (most recent call last):
  File "/root/llm-on-ray/examples/inference/api_server_openai/query_http_requests.py", line 90, in <module>
    raise e
  File "/root/llm-on-ray/examples/inference/api_server_openai/query_http_requests.py", line 85, in <module>
    choices = json.loads(chunk)["choices"]
KeyError: 'choices'

Server log:

> (ServeReplica:router:Router pid=17033) handle_request:  {'model_id': 'Qwen1.5-110B'}
(ServeReplica:router:Router pid=17033) [ERROR 2024-06-11 06:45:50,784] request_handler.py: 135  Request chatcmpl-2f874a090e464838a808dc49c35d7b59 failed with:
(ServeReplica:router:Router pid=17033) Traceback (most recent call last):
(ServeReplica:router:Router pid=17033)   File "/root/llm-on-ray/llm_on_ray/inference/api_openai_backend/request_handler.py", line 118, in handle_request
(ServeReplica:router:Router pid=17033)     async for response in async_iterator:
(ServeReplica:router:Router pid=17033)   File "/usr/local/lib/python3.10/dist-packages/ray/serve/handle.py", line 662, in __anext__
(ServeReplica:router:Router pid=17033)     next_obj_ref = await self._obj_ref_gen.__anext__()
(ServeReplica:router:Router pid=17033)   File "python/ray/_raylet.pyx", line 332, in __anext__
(ServeReplica:router:Router pid=17033)   File "python/ray/_raylet.pyx", line 508, in _next_async
(ServeReplica:router:Router pid=17033)   File "/usr/lib/python3.10/asyncio/tasks.py", line 384, in wait
(ServeReplica:router:Router pid=17033)     return await _wait(fs, timeout, return_when, loop)
(ServeReplica:router:Router pid=17033)   File "/usr/lib/python3.10/asyncio/tasks.py", line 491, in _wait
(ServeReplica:router:Router pid=17033)     await waiter
(ServeReplica:router:Router pid=17033) asyncio.exceptions.CancelledError
(ServeReplica:router:Router pid=17033) INFO 2024-06-11 06:45:50,788 router_Router ov1clcw4 b2e28da1-2d9f-4582-9731-cb8e9868a138 /v1/chat/completions replica.py:373 - __CALL__ OK 1800095.6ms

**Comment by carsonwang** [comment]
Close this. Qwen/Qwen2-7B-Instruct is the correct model to validate.
