### ISSUE TITLE
ERROR when I start webui

### ISSUE THREAD

**Issue by dandiago** [intel/llm-on-ray#280]
I use command python -m llm_on_ray.ui.start_ui --node_user_name llm-on-ray --conda_env_name llm-on-ray --master_ip_port "192.168.124.224:6379" to start webui. But there is an error:
python -m llm_on_ray.ui.start_ui --node_user_name llm-on-ray --conda_env_name llm-on-ray --master_ip_port "$node_ip:6379"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/dandiago/llm-on-ray/llm_on_ray/ui/start_ui.py", line 39, in <module>
    from pyrecdp.LLM import TextPipeline
ModuleNotFoundError: No module named 'pyrecdp.LLM'

**Comment by dandiago** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-text-splitters 0.2.4 requires langchain-core<0.3.0,>=0.2.38, but you have langchain-core 0.1.23 which is incompatible.
langfuse 2.44.0 requires anyio<5.0.0,>=4.4.0, but you have anyio 3.7.1 which is incompatible.
langchain-chroma 0.1.4 requires langchain-core<0.4,>=0.1.40; python_version >= "3.9", but you have langchain-core 0.1.23 which is incompatible.

  Running command git submodule update --init --recursive -q
  fatal: unable to access 'https://github.com/facebookresearch/dlrm.git/': Could not resolve host: github.com
  fatal: clone of 'https://github.com/facebookresearch/dlrm.git' into submodule path '/tmp/pip-install-g2pte0td/pyrecdp_352f075c32af4255adfc9f1a95aa6884/modelzoo/third_party/dlrm' failed
  Failed to clone 'modelzoo/third_party/dlrm'. Retry scheduled
  fatal: unable to access 'https://github.com/mlcommons/training_results_v1.0.git/': Could not resolve host: github.com
  fatal: clone of 'https://github.com/mlcommons/training_results_v1.0.git' into submodule path '/tmp/pip-install-g2pte0td/pyrecdp_352f075c32af4255adfc9f1a95aa6884/modelzoo/third_party/mlperf_v1.0' failed
  Failed to clone 'modelzoo/third_party/mlperf_v1.0'. Retry scheduled
  fatal: unable to access 'https://github.com/MIC-DKFZ/nnUNet.git/': Could not resolve host: github.com
  fatal: clone of 'https://github.com/MIC-DKFZ/nnUNet.git' into submodule path '/tmp/pip-install-g2pte0td/pyrecdp_352f075c32af4255adfc9f1a95aa6884/modelzoo/third_party/nnUNet' failed
  Failed to clone 'modelzoo/third_party/nnUNet'. Retry scheduled
  fatal: unable to access 'https://github.com/bats-core/bats-core.git/': Could not resolve host: github.com
  fatal: clone of 'https://github.com/bats-core/bats-core.git' into submodule path '/tmp/pip-install-g2pte0td/pyrecdp_352f075c32af4255adfc9f1a95aa6884/tests/cicd/bats' failed
  Failed to clone 'tests/cicd/bats'. Retry scheduled
  fatal: unable to access 'https://github.com/bats-core/bats-assert.git/': Could not resolve host: github.com
  fatal: clone of 'https://github.com/bats-core/bats-assert.git' into submodule path '/tmp/pip-install-g2pte0td/pyrecdp_352f075c32af4255adfc9f1a95aa6884/tests/cicd/test_helper/bats-assert' failed
  Failed to clone 'tests/cicd/test_helper/bats-assert'. Retry scheduled
  fatal: unable to access 'https://github.com/ztombol/bats-file.git/': Could not resolve host: github.com
  fatal: clone of 'https://github.com/ztombol/bats-file.git' into submodule path '/tmp/pip-install-g2pte0td/pyrecdp_352f075c32af4255adfc9f1a95aa6884/tests/cicd/test_helper/bats-file' failed
  Failed to clone 'tests/cicd/test_helper/bats-file'. Retry scheduled
  fatal: unable to access 'https://github.com/bats-core/bats-support.git/': Could not resolve host: github.com
  fatal: clone of 'https://github.com/bats-core/bats-support.git' into submodule path '/tmp/pip-install-g2pte0td/pyrecdp_352f075c32af4255adfc9f1a95aa6884/tests/cicd/test_helper/bats-support' failed
  Failed to clone 'tests/cicd/test_helper/bats-support'. Retry scheduled
  fatal: unable to access 'https://github.com/facebookresearch/dlrm.git/': Could not resolve host: github.com
  fatal: clone of 'https://github.com/facebookresearch/dlrm.git' into submodule path '/tmp/pip-install-g2pte0td/pyrecdp_352f075c32af4255adfc9f1a95aa6884/modelzoo/third_party/dlrm' failed
  Failed to clone 'modelzoo/third_party/dlrm' a second time, aborting
  error: subprocess-exited-with-error

  × git submodule update --init --recursive -q did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git submodule update --init --recursive -q did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
