### ISSUE TITLE
Gettign error while running start_ui.py

### ISSUE THREAD

**Issue by dkiran1** [intel/llm-on-ray#64]
I I followed the steps mentioned in setup file to build dcoker image for Gaudi 
https://github.com/intel/llm-on-ray/blob/main/docs/setup.md, I could run the ray server using below command
ray start --head --node-ip-address 127.0.0.1 --dashboard-host='0.0.0.0' --dashboard-port=8265
I ran python -u ui/start_ui.py --master_ip_port "$node_ip:6379" since I could not figure out where to get node_user_name , conda_env_name name from the below command
python -u ui/start_ui.py --node_user_name $user --conda_env_name $conda_env --master_ip_port "$node_ip:6379"
I got many missing installations error, I installed the missing ones After that Iam getting the below error while installing. Can I please know what I might me missing , where to get node_user)name and conda_env_name from?

Error while connecting to Ray UI
Traceback (most recent call last):
  File "/root/llm-ray/ui/start_ui.py", line 26, in <module>
    from inference.predictor_deployment import PredictorDeployment
  File "/root/llm-ray/ui/../inference/predictor_deployment.py", line 21, in <module>
    from ray import serve
  File "/usr/local/lib/python3.10/dist-packages/ray/serve/__init__.py", line 4, in <module>
    from ray.serve.api import (
  File "/usr/local/lib/python3.10/dist-packages/ray/serve/api.py", line 15, in <module>
    from ray.serve.built_application import BuiltApplication
  File "/usr/local/lib/python3.10/dist-packages/ray/serve/built_application.py", line 7, in <module>
    from ray.serve.deployment import Deployment
  File "/usr/local/lib/python3.10/dist-packages/ray/serve/deployment.py", line 22, in <module>
    from ray.serve.context import _get_global_client
  File "/usr/local/lib/python3.10/dist-packages/ray/serve/context.py", line 12, in <module>
  File "/usr/local/lib/python3.10/dist-packages/ray/serve/_private/client.py", line 28, in <module>
    from ray.serve._private.deploy_utils import get_deploy_args
  File "/usr/local/lib/python3.10/dist-packages/ray/serve/_private/deploy_utils.py", line 8, in <module>
    from ray.serve.schema import ServeApplicationSchema
  File "/usr/local/lib/python3.10/dist-packages/ray/serve/schema.py", line 141, in <module>
    class DeploymentSchema(BaseModel, allow_population_by_field_name=True):
  File "/usr/local/lib/python3.10/dist-packages/ray/serve/schema.py", line 269, in DeploymentSchema
    def num_replicas_and_autoscaling_config_mutually_exclusive(cls, values):
  File "/usr/local/lib/python3.10/dist-packages/pydantic/deprecated/class_validators.py", line 231, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

**Comment by KepingYan** [comment]
What is the version of `pydantic`? Could you downgrade it to 1.10 and try again? By the way, web ui has only been tested on Intel CPU, I'm not sure if it can run successfully on Guadi. And it needs to use the environment created by conda/miniconda, so the `conda_env_name` is the name of environment used. `node_user_name` is the username of the node or docker container.
